# Example: https://github.com/getsentry/sentry/blob/2ebe01feab863d89aa7564e6d243b6d80c230ddc/.github/file-filters.yml
hcl: &hcl
  - '**/*.hcl'

tf: &tf
  - '**/*.tf'

terragrunt_all:
  - '**/terragrunt.hcl'