# TODO: Detect changes in _envcommon folder and run commands in terragrunt folders with changed modules
# TODO: Detect changes in terraform modules and run commands in terragrunt folders with changed modules
name: Terragrunt CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  tf_version: '1.4.4'
  tg_version: '0.48.1'

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      terragrunt_all: ${{ steps.changes.outputs.terragrunt_all }}
      changed_folders: ${{ steps.get-changed-folders.outputs.CHANGED_FOLDERS }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Filter paths
        id: changes
        uses: dorny/paths-filter@v3
        with:
          list-files: shell
          filters: |
            terragrunt_all:
              - '**/terragrunt.hcl'
            hcl_all:
              - '**/*.hcl'
      
      - name: Get changed folders
        id: get-changed-folders
        run: |
          echo "Changed terragrunt files: ${{ steps.changes.outputs.terragrunt_all_files }}"
          echo "Changed HCL files: ${{ steps.changes.outputs.hcl_all_files }}"          
          CHANGED_FOLDERS=$(echo "${{ steps.changes.outputs.hcl_all_files }}" | xargs -n1 dirname | sort -u)
          
          ### If `terragrunt run-all <command>` doesnt do the trick, we can use the following to detect subfolders with terragrunt.hcl
          # Detect sub-folders of CHANGED_FOLDERS with terragrunt.hcl in it and write to variable
          # for FOLDER in $CHANGED_FOLDERS; do
          #   $SUB_FOLDERS=$(find $FOLDER -name terragrunt.hcl -exec dirname {} \; | sort -u)
          #   # If there are more than 1 subfolders, add them to CHANGED_FOLDERS
          #   if [ $(echo $SUB_FOLDERS | wc -w) -gt 1 ]; then
          #     CHANGED_FOLDERS="$CHANGED_FOLDERS $SUB_FOLDERS"
          #   fi
          # done
          
          echo "CHANGED_FOLDERS=$CHANGED_FOLDERS" >> $GITHUB_OUTPUT
        shell: bash

  plan-any:
    if: ${{ needs.detect-changes.outputs.terragrunt_all == 'true' }}
    needs: detect-changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: ${{ fromJSON(needs.detect-changes.outputs.changed_folders) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Terragrunt plan
      #   uses: gruntwork-io/terragrunt-action@v2
      #   with:
      #     tf_version: ${{ env.tf_version }}
      #     tg_version: ${{ env.tg_version }}
      #     tg_command: plan
      #     tg_dir: ${{ matrix.folder }}

      - name: Echo
        run: |
          echo "do something in: ${{ matrix.folder }} folder"
