# TODO: Detect changes in _envcommon folder and run commands in terragrunt folders with changed modules
# TODO: Detect changes in terraform modules and run commands in terragrunt folders with changed modules
# TODO: Fix detection of changed folders if parent folder is changed https://github.com/yevhen-kalyna/terragrunt-ci-example/actions/runs/7790973748/job/21246013458
name: Terragrunt CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  tf_version: '1.4.4'
  tg_version: '0.48.1'

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      terragrunt_all: ${{ steps.changes.outputs.terragrunt_all }}
      changed_folders: ${{ steps.get-changed-folders.outputs.CHANGED_FOLDERS }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Filter paths
        id: changes
        uses: dorny/paths-filter@v3
        with:
          list-files: shell
          filters: |
            terragrunt_all:
              - 'terragrunt/**/terragrunt.hcl'
            terraform_all:
              - 'terraform/**/*.tf'
            envcommon_all:
              - 'terragrunt/_envcommon/**/*'
            hcl_all:
              - '**/*.hcl'
      - name: Get changed folders
        id: get-changed-folders
        run: |
          # Will set CHANGED_FOLDERS as JSON array
          .github/parse_paths.py ${{ steps.changes.outputs.terraform_all_files }} ${{ steps.changes.outputs.hcl_all_files }}
        shell: bash

  plan-any:
    if: ${{ needs.detect-changes.outputs.terragrunt_all == 'true' }}
    needs: detect-changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: ${{ fromJSON(needs.detect-changes.outputs.changed_folders) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Terragrunt plan
      #   uses: gruntwork-io/terragrunt-action@v2
      #   with:
      #     tf_version: ${{ env.tf_version }}
      #     tg_version: ${{ env.tg_version }}
      #     tg_command: plan
      #     tg_dir: ${{ matrix.folder }}

      - name: Echo
        run: |
          echo "do something in: ${{ matrix.folder }} folder"
